CPA_App/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("comments.urls", namespace="comments")),
    path('captcha/', include('captcha.urls')),

]

comments/urls.py
from django.urls import path

from comments.views import CommentCreateView, CommentListView, CommentDetailView

urlpatterns = [
    path("create/", CommentCreateView.as_view(), name="comment-create"),
    path("", CommentListView.as_view(), name="comment-list"),
    path("comments/<int:pk>/", CommentDetailView.as_view(), name="comment-detail"),
]

app_name = "comments"

comments/models.py
import re

from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.db import models


class Comment(models.Model):
    ALLOWED_TAGS_REGEX = r'^<(a|code|i|strong)>(.*?)<\/(a|code|i|strong)>$'

    allowed_tags_validator = RegexValidator(
        regex=ALLOWED_TAGS_REGEX,
        message='Only <a>, <code>, <i>, and <strong> tags are allowed.',
    )

    alphanumeric_validator = RegexValidator(
        regex=r'^[a-zA-Z0-9]+$',
        message='Only Latin letters and digits are allowed.',
    )

    username = models.CharField(
        max_length=255, null=False, blank=False,
        validators=[alphanumeric_validator]
    )
    email = models.EmailField(null=False, blank=False)
    homepage = models.URLField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    text = models.TextField(
        null=False, blank=False,
        # validators=[allowed_tags_validator]
    )
    parent = models.ForeignKey(
        'self', on_delete=models.CASCADE,
        null=True, blank=True, related_name='replies'
    )

    def clean(self):
        super().clean()
        self.validate_html_tags()

    def validate_html_tags(self):
        if "<" not in self.text:
            return
        if not re.match(self.ALLOWED_TAGS_REGEX, self.text):
            raise ValidationError('Only <a>, <code>, <i>, and <strong> tags are allowed.')

    def __str__(self):
        return f"Comment by {self.username}"

    def get_replies(self):
        return self.replies.all()

    class Meta:
        ordering = ["-created_at"]

comments/forms.py
from django import forms
from comments.models import Comment
from captcha.fields import CaptchaField


class CommentForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Comment
        fields = ["username", "email", "homepage", "text"]
        widgets = {
            'text': forms.Textarea(attrs={'rows': 5}),
        }

    def clean_homepage(self):
        homepage = self.cleaned_data.get('homepage')
        if homepage and not homepage.startswith(('http://', 'https://')):
            homepage = f'http://{homepage}'
        return homepage

comments/views.py
from django.urls import reverse_lazy
from django.views import generic

from comments.forms import CommentForm
from comments.models import Comment


class CommentListView(generic.ListView):
    model = Comment
    template_name = "comment_list.html"
    paginate_by = 25


class CommentCreateView(generic.CreateView):
    model = Comment
    form_class = CommentForm
    template_name = "comment_form.html"
    success_url = reverse_lazy("comments:comment-list")


class CommentDetailView(generic.DetailView):
    model = Comment
    template_name = "comment_detail.html"

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Comments</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
{#    {% load static %}#}
{#    <link rel="stylesheet" href="{% static 'css/styles.css' %}">#}
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
{#                {% include "includes/sidebar.html" %}#}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

            {% block pagination %}
{#                {% include "includes/pagination.html" %}#}
            {% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/comment_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} comment</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/comment_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Comments list
    <a href="{% url 'comments:comment-create' %}" class="btn btn-primary link-to-page">
      Create comment
    </a>
  </h1>
  {% if comment_list %}
    <ul>
      {% for comment in comment_list %}
        <li>

          {{ comment.text }} <br>
            <a href="{% url 'comments:comment-create' %}" class="btn btn-primary link-to-page">
                      Reply
            </a>
            {{ comment.get_replies }}
{#            <a href="{% url "taxi:car-detail" pk=car.id %} ">{{ car.id }}</a>#}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Comments are not exist yet</p>
  {% endif %}
{% endblock %}